# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12b37057d7c9273ec1b8e8f128960827118439771439da01ff2fe2571242e06399bd03f0cab2f335cf184f84de549ef08299f4bf8217bfb8859d3152a8464c4c

test:
  secret_key_base: 46b39a289c1db57fe50544fa412aebbf43f295ad6526e1ef7b5eba2beba43f54e913a9b4dc143e1d4b8683be0eef681039e8c56e37ced3a9e37321704afde8d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
